### ISSUE TITLE
Bài tập nhóm - BDD

### ISSUE THREAD

**Issue by truonganhhoang** [truonganhhoang/INT2208-2-2017#346]
Cập nhật tài liệu readme.md của nhóm mô tả:
- [ ] Tên nhóm, các thành viên nhóm.
- [ ] Ứng dụng gốc tham khảo để làm lại.
- [ ] Sơ đồ [ca sử dụng](https://en.wikipedia.org/wiki/Use_case) của ứng dụng nhóm đang thực hiện.
- [ ] Mỗi ca sử dụng có một thiết kế giao diện bằng html và bootstrap thuần (không dùng thêm css khác).
- [ ] Link đến mô tả các kịch bản của ca sử dụng bằng [Cucumber]
(https://github.com/cucumber/cucumber/wiki/A-Table-Of-Content) sau khi đã làm phần ứng dụng sau.

Với dự án nhóm, các nhóm thực hiện:
- [ ] Chọn khung ứng dụng (khuyến cáo Rails, Angular 2, Ionic 2) (https://hotframeworks.com/)
- [ ] Đưa các màn hình giao diện vào khung ứng dụng đã lựa chọn.
- [ ] Viết các step definitions dựa trên giao diện html đã đưa vào khung ứng dụng.
- [ ] Chạy các kịch bản kiểm thử chấp thuận và dựa vào kết quả kiểm thử để cài đặt dần ứng dụng.

Hạn: 16:00 ngày 26/3/2017. Từ 17:00 ngày 26/3/2017 các nhóm nhận xét bài của nhau theo thứ tự sau, nhóm trên nhận xét nhóm dưới, nhóm cuối nhận xét nhóm đầu. Viết nhận xét và chấm điểm nhóm theo các tiêu chí trên, điền điểm vào cột R trong file danh sách lớp. Các nhóm điền repo của nhóm mình vào sheet [Repos các Nhóm] (https://docs.google.com/spreadsheets/d/1LoIZe9N-zBik0BWb6umfTJdI-w7ZVp2vo1JU-ax-bS0/edit#gid=1352130950) để nhóm chấm sẽ chấm trực tiếp trên repo của nhóm được chấm. 
VIRUS
TTAC
SML
NTT
No Name
Moonlight
MIDF
LSE
LOL2VN
K59 
IT
HMH
HL308
H3T
Fallen blossom
ĐMX
Corgi
Con Rùa
BKA
ATTT

**Comment by dungtt8** [comment]
Thầy có thể cho bọn em xem ví dụ hoàn chỉnh của kịch bản và step definitions  của một app cụ thể không ạ. Thực sự thì hầu hết các nhóm đang bị mất phương hướng ạ!

**Comment by truonganhhoang** [comment]
Video hướng dẫn về cucumber:
- https://cucumber.io/school
- https://blog.codeship.com/cucumber-bdd/

**Comment by nguyentienviet123456** [comment]
Thầy và các bạn cho mình hỏi chọn khung ứng dụng là thế nào nhỉ -(khuyến cáo Rails, Angular 2, Ionic 2) 
Có phải là code bằng một trong các ngôn ngữ đó không nhỉ ???? :v :v :v

**Comment by DamDinhDinh** [comment]
Ai làm rồi hướng dẫn qua giúp với! Giờ nếu chọn framework (vd: Angular 2) thì chuyển hết code file HTML sang code component à?

**Comment by truonganhhoang** [comment]
Các nhóm dùng Angular2 có thể fork repo này để bắt đầu làm ứng dụng.

https://github.com/AngularClass/angular2-webpack-starter

học AngularJS thì học bản 2.0 trở lên, ở trang này

http://courses.angularclass.com/p/angular-2-fundamentals

**Comment by truonganhhoang** [comment]
tham khảo thêm https://openclassrooms.com/courses/test-your-website-s-interface
