### ISSUE TITLE
Bài tập về nhà cá nhân tuần 11

### ISSUE THREAD

**Issue by truonganhhoang** [truonganhhoang/INT2208-2-2017#374]
Hoàn thành khóa học: 
https://openclassrooms.com/courses/test-your-website-s-interface

**Comment by nguyentienviet123456** [comment]
thầy ơi em không hiểu ý nghĩa của 3 cái test yêu cầu ạ :)

**Comment by truonganhhoang** [comment]
Em hỏi cụ thể hơn xem.

**Comment by nguyentienviet123456** [comment]
should properly calculate a gutter game
should properly calculate a strike
should properly calculate a spare
đề bài yêu cầu test 3 vấn đề này, có ví dụ thứ nhất nhưng em không hiểu luật chơi

**Comment by truonganhhoang** [comment]
Mĩnh nghĩ các em tự tìm hiểu được, chịu khó search trên mạng, vì mình cũng
phải search như các em.

http://blog.happybowlers.com/bowling-va-goc-nhin-ve-cuoc-song/

https://vi.wikipedia.org/wiki/Bowling

https://en.wikipedia.org/wiki/Ten-pin_bowling#Rules_and_regulations

**Comment by nguyentienviet123456** [comment]
em cảm ơn thầy !
