### ISSUE TITLE
Bài tập nhóm tuần 11-14: Triển khai ứng dụng của nhóm 

### ISSUE THREAD

**Issue by truonganhhoang** [truonganhhoang/INT2208-2-2017#375]
1. Cài Google Analytics vào ứng dụng của nhóm.
2. Triển khai dự án của nhóm cho chạy trên https://www.heroku.com/ hoặc một dịch vụ tương tự.
3. Hoàn thiện trang giới thiệu, hướng dẫn sử dụng, thu hút người dùng.
4. Thu hút người dùng vào sử dụng, thể hiện tốt các chỉ số trên Analytics, trang fanpage, facebook, v.v..  thêm các tính năng comment của facebook, hay của https://disqus.com/ hay dịch vụ tương tự.

**Comment by quita2004** [comment]
Thầy cho e hỏi hoàn thiện trang giới thiệu, hướng dẫn sử dụng là làm những gì ạ?

**Comment by truonganhhoang** [comment]
Các thông tin giới thiệu, thông tin trên footer, header mà các em thấy thường có trên các sản phẩm..

**Comment by quita2004** [comment]
Thầy có thể cho e 1 ví dụ cụ thể được không ạ?

**Comment by ThuLeHoang** [comment]
Thưa thầy. Sao tự nhiên không clone được repo của nhóm mình ạ? Những lần em commit đều không được, chỉ hiện lên history của mình?
Hôm nay lại không clone và commit được. Mỗi lần click vào open in desktop là nó chuyển sang trang này 
![image](https://cloud.githubusercontent.com/assets/25579743/25861478/10f0787c-350f-11e7-9948-89b53ff2f3b4.png)
