### ISSUE TITLE
Báo cáo dự án môn học

### ISSUE THREAD

**Issue by truonganhhoang** [truonganhhoang/INT2208-2-2017#376]
Mỗi nhóm tạo một chương để viết báo cáo vào link sau:
https://www.gitbook.com/book/truonganhhoang/int2208-2-2017/

Hạn: trước buổi học cuối cùng của môn học (tuần 15)

**Comment by ThuLeHoang** [comment]
Thưa thầy. Làm sao để tạo 1 chương trong gitbook của thầy ạ?

**Comment by truonganhhoang** [comment]
Em edit, rồi add article ở bên trái đc ko?

**Comment by tuananh97** [comment]
Thưa thầy, Em không thấy nút Edit thầy ạ, thấy mỗi nút Read thôi ạ

**Comment by ThuLeHoang** [comment]
![image](https://cloud.githubusercontent.com/assets/25579743/25773109/fb5d416c-32a1-11e7-8c64-b5949d93f9cb.png)
e chỉ thấy Read thôi ạ

**Comment by truonganhhoang** [comment]
mình mới thêm tài khoản ThuLeHoang  của em rồi, em thử lại xem.. phải dùng đúng tài khoản mình add thì phải được, có bạn khác cập nhật được rồi.

**Comment by truonganhhoang** [comment]
Nhiều bạn chưa nhận lời mời:

![image](https://cloud.githubusercontent.com/assets/711995/25773647/474177fc-32ab-11e7-9744-ddac3c480f51.png)

**Comment by tuananh97** [comment]
Thầy gửi lời mời làm collaborate vào gmail ấy bạn, đăng nhập bằng tài khoản thầy mời đấy là sửa được
[VD](https://lh3.googleusercontent.com/1F0JdqqOa85wLrrx7FyMf-HeGEBmdIR17PeANBOusNhR1G9eUREK0Tatx7bnrAob19SwBGzA8ttSDI3BUuVnn_k9IIoU9zn7yCzdSFnEXc2Wzf223BfdqjGhLX9cIgu1xiA5eqNTQ2nE29Q1dsN3dqe26oyR46ocIRsLX45LLhP8p1kMh4DgPttDYL9MO7APQBCyBx71WKkfisUb0j5Eibx1vmffh0aElBclVtdQ5kQKu6LMYYtorLSq3_p11BknhXbBqGQhu8icWtlBat3g0rDpBVLzdGjiU7LkIOmDJZi30Ytb_RlEF6mIzE_iJ1COVRWpl77B8tCho5qDWCtgb9R6UN3rTHlqmWzOUhABv2BKmKx_iBPpwPruIOBLEnTleHwmw2LutWtmiCYIgW4WSrygCR5jmGI3s0g1xjsPxaOxSMHscU21MDrBOWFyzxlk-SIqccAzt_uzAWZbTdNzuOUOdmxzRaDW4zUi0uLRtzKXQn528hIYolENAkXDw7Hbguulftvlg7BUmN6NEG228rUWbFfRCrqCV5o98BkS7i5HG5uhkGjqcTdqgdEgq2C80FbsPcvcq9SOsvV5CVva3UF9IkSq27-sYmLOKtwT7TZ-bL_fL9cx=w611-h613-no)

**Comment by quita2004** [comment]
cái này có phải viết bằng markdown ko thầy?

**Comment by truonganhhoang** [comment]
Nó chính là markdown.

**Comment by quita2004** [comment]
thưa thầy sao e viết bằng markdown mà no ko hiển thị như mong muốn ạ?
![capture](https://cloud.githubusercontent.com/assets/25577370/25779115/cb4740ec-333a-11e7-92ea-586804f6d3d3.PNG)

**Comment by quita2004** [comment]
thưa thầy sao e viết bằng markdown mà no ko hiển thị như mong muốn ạ?
![image](https://cloud.githubusercontent.com/assets/25577370/25779123/e85e26f0-333a-11e7-815d-1a61eadeb4fb.png)

**Comment by truonganhhoang** [comment]
à, ở góc phải, phía dưới nó có menu để chuyển sang chế độ
markdown,  còn ở chế độ này thì có toolbar ở trên để chọn h1,
h2.. rồi.

**Comment by thotranuet97** [comment]
Thưa thầy, em vẫn chưa có quyền edit, làm sao để nhận lời mời ạ?

**Comment by truonganhhoang** [comment]
Mình mời theo email các em cung cấp ở Gsheets.

2017-05-07 22:12 GMT+07:00 thotranuet97 <notifications@github.com>:
