### ISSUE TITLE
Bài tập nhóm - thiết kế màn hình giao diện ban đầu cho dự án của nhóm

### ISSUE THREAD

**Issue by truonganhhoang** [truonganhhoang/INT2208-2-2017#82]
1. Các nhóm thảo luận để chọn một ứng dụng đơn giản, làm lại nó. Gợi ý: dùng các dự án có trong slide số 0, hoặc chọn một số app phục vụ giáo dục, làm lại nó.

2. Sau khi thống nhất dự án trong nhóm, thiết kế ít nhất mỗi người 1 màn hình giao diện, chọn các màn hình giao diện quan trọng nhất của ứng dụng làm trước, với đầy đủ chi tiết bằng một số công cụ thiết kế giao diện dựa trên bootstrap framework. Gợi ý, tìm trên google với từ khóa: bootstrap mockup để tìm một công cụ để làm giao diện cho ứng dụng của nhóm.

3. Làm tài liệu thuyết trình ứng dụng bằng file markdown với tên: readme.md và để trong thư mục với tên thư mục là Nhom-<tên của nhóm>. Gợi ý, có thể sử dụng [paper.dropbox.com](https://db.tt/OXzLvAgu) để các thành viên trong nhóm cùng soạn thảo được đồng thời, rồi xuất ra file markdown để nộp vào github. Trưởng nhóm tạo pull request sau khi hoàn thành bài tập nhóm.

Hạn: Chủ Nhật tuần tới 26/2/2017.

**Comment by truonganhhoang** [comment]
Ra hạn và yêu thêm cho các nhóm về bài tập nhóm:

1. Mỗi nhóm chọn một app nhỏ, đã có trên play store, để làm lại. 

2. Mỗi người làm ít nhất một màn hình chức năng chính của dự án nhóm bằng bootstrap thuần, không sử dụng thêm các css riêng. Không hardcode trong html.

3. Đặt tên các files ảnh màn hình sau khi thiết kế kèm theo mã html bằng các file 1.jpg 1.html, 2.jpg, 2.html, v.v.. vào thư mục của nhóm. Trong file html, link đến file bootstrap trên mạng (bootstrap cdn).

Hạn: 4/3/2017. Ngày 5/3 sẽ chấm điểm.

Chú ý: Ngoài ra, các thành viên trong nhóm kiểm tra chéo bài tập về nhà cá nhân của nhau, điểm sẽ chấm dựa trên bài kém nhất của cả nhóm.

**Comment by phamngocsonls** [comment]
thầy ơi cho em hỏi là bắt buộc phải làm trên nên web hay làm ở di động được không thầy

**Comment by xuanvuong97** [comment]
Thưa thầy em dùng ionic có được không ạ?

**Comment by truonganhhoang** [comment]
làm ionic cũng đc.

**Comment by truonganhhoang** [comment]
Các nhóm hoàn thiện bài tập nhóm đến hết ngày 8/3/2017. Từ 8-10/3 các nhóm chấm điểm nhóm khác và viết nhận xét về các nhóm khác bằng cách comment vào issue này dựa trên thứ tự các nhóm trong danh sách dưới đây, nhóm trên chấm nhóm dưới, nhóm cuối cùng chấm nhóm đầu tiên. Điểm của người thấp nhất 50%, điểm bài tập dự án của nhóm 50%, chấm theo các yêu cầu đã nêu của issue như file readme.md, các ảnh màn hình và html có theo qui định không, và chất lượng của các comments khi commits. Nhập điểm vào cột Q ở file Google Sheet danh sách lớp.

ATTT
BKA
Conrua
Corgi
H3T
MIDF
Moonlight
S.M.L
VIRUS
FallenBlossom
HMH
LSE
NoName
TTAC
DMX
K59
LOL2VN
HL308 (mới bổ sung)

**Comment by truonganhhoang** [comment]
# Chú ý về việc commit. 
Để hạn chế pull requests đến repo chính của lớp, các nhóm sẽ nộp bài vào repo của trưởng nhóm, sau đó trưởng nhóm tạo pull request để nộp bài của cả nhóm cho giáo viên. Nhóm trưởng add các thành viên vào collaborators của repo của mình để các bạn commit trực tiếp, hoặc các thành viên fork repo của nhóm trưởng ra, rồi tạo pull quest khi làm xong, khi merge vào nhóm trưởng sẽ review và kiểm soát đc chất lượng của nhóm.

**Comment by tranthang1997** [comment]
Em thưa thầy, nhóm em là nhóm HL308 tại sao lại không có trong danh sách nhóm chấm điểm ở trên ạ?

**Comment by nguyentienviet123456** [comment]
Thưa thầy em có ý kiến, ngày mai mùng 8 tháng 3, chị em phấn khởi đi ra đi vào, chúng em xin thầy lùi hạn làm bt nhóm vào ngày mùng 9 tháng 3 được không ạ

**Comment by TranHongngoc** [comment]
Thưa thầy sao nhóm NTT chưa có tên trong danh sách?

**Comment by truonganhhoang** [comment]
Mình lấy các nhóm có tên bắt đầu bằng Nhom- trên repo.. nên nếu các nhóm làm sai sẽ bị sót.

**Comment by HieuTrungNguyen** [comment]
Thầy có thể merge các pull chỉnh sửa của các nhóm để bọn em chấm điểm được không ạ??

**Comment by trongmanh19** [comment]
thưa thầy sao nhóm HMH không được merge lại bt nhóm vậy ạ ???

**Comment by truonganhhoang** [comment]
mình merge tất cả các request ko bị conflicts rồi.. thiếu nhóm nào các em tạo pull request lại.

**Comment by truonganhhoang** [comment]
các nhóm còn lại chưa có trong danh sách thì review chéo nhau.. nếu chỉ có 1 nhóm thì mình sẽ review.

**Comment by phamngocsonls** [comment]
Thầy ơi cho em xin link chấm điểm của lớp. Hôm trước em thấy mà hnay không thấy nữa

**Comment by HieuTrungNguyen** [comment]
nhóm BKA nhận xét nhóm Con Rùa: Tuy file readme chưa nêu tên các thành viên trong nhóm, nhưng còn lại các bạn hoạt động nhóm khá tốt :+1:

**Comment by anhnt97** [comment]
Nhóm Con rùa nhận xét nhóm Corgi : Giao diện tương đối ổn nhưng đơn giản , màn hình số 3,4 không được đồng nhất lắm với màn hình 1,2 .Giao diện còn tương đối đơn giản, file readme chưa nêu tên từng thành viên. Commit trên github "rename + update " còn chung chung chưa cụ thể.Trang web đã sử dụng bootstrap thuần.Các bạn trong nhóm đã hoàn thành xong 100% bài tập của 4 tuần đầu.

**Comment by tuananh97** [comment]
**Nhóm FallenBlossom** nhận xét **nhóm HMH:** Đặt tên nhóm sai format
**Bài tập cá nhân** các bạn trong nhóm đã nộp đủ 100% đặt tên đúng, chỉ có bạn HoangDuyHao chưa xoá các file sai tên. 
**Bài tập nhóm** đặt tên ảnh và html đúng yêu cầu, các giao diện vẽ tương đối đầy đủ chức năng, và đồng nhất với nhau. 
**_File html_**: đã sử dụng bootstrap thuần, link với bootstrap CDN, code dễ hiểu,..
**_File Readme_** đã nêu tên các thành viên, nội dung thì hơi ngắn nhưng đã nêu được ý tưởng, xu hướng cải tiến phần mềm
**_Commit trên github_** thì đã ổn, người đọc dễ hiểu đã làm gì

**Comment by tranthang1997** [comment]
Nhóm HL308 nhận xét nhóm ATTT:
Bài tập nhóm: Giao diện tương đối tốt, đầy đủ, sử dụng bootrap ổn nhưng còn lỗi phần menu ở file 4 chưa được tốt, file readname đúng, đủ yêu cầu
Bài tập cá nhân: 100% các bạn trong nhóm hoàn thành tốt bài tập, tuy nhiên có bạn NguyenAnhTuan đặt tên file chưa đúng yêu cầu

**Comment by ChuThom610** [comment]
Nhóm H3T nhận xét nhóm MIDF: 
- Bài tập cá nhân: 
              + Các thành viên trong nhóm đã nộp đủ 100% lượng bài tập.
              + Ngoại trừ bạn UongThiVan thì các bạn còn lại còn đặt tên ảnh sai format (html&css.png,         makeawebsite.png).
- Bài tập nhóm: 
              + Số lượng ảnh và file html tối thiểu đủ, đặt tên đúng format yêu cầu.
              + Các giao diện khá thống nhất và thể hiện được chức năng mong muốn.
              + File .html: có sử dụng bootstrap thuần, nhưng còn hardcode, có link bootstrap CDN, không có css riêng.
              + File readme: đặt tên sai format (README.md), đã nêu đủ tên thành viên, link tham khảo, các chức năng, có đối tượng hướng tới (nhưng chưa nói cụ thể, nên giới hạn độ tuổi như thế nào), và nên miêu tả phần mềm cụ thể hơn nữa.
             + Chất lượng commit: thể hiện được mục đích commit, người đọc dễ hiểu.

**Comment by phamngocsonls** [comment]
Nhóm LOL2VN nhận xét nhóm HL308
Bài tập cá nhân các bạn trong nhóm có NguyenHongSon thiếu Ruby on rails.
Bài tập nhóm đặt tên ảnh và html đúng yêu cầu, các giao diện vẽ tương đối đầy đủ chức năng, và đồng nhất với nhau.
File html: đã sử dụng bootstrap thuần, link với bootstrap CDN
File Readme đã nêu tên các thành viên, nội dung đủ.
Commit của NguyenHongSon va PhamMinhNgoc không đúng chủ đề ( 2 người commit "b" và "c")

**Comment by ThanhHuyen25** [comment]
Nhóm MIDF nhận xét nhóm Moonlight
Bài tập cá nhân: các bạn đều hoàn thành đúng và đầy đủ, đặt tên và commit đúng
Bài tập nhóm: 
+ tên: mat.png không phải là màn hình chức năng và đặt tên sai, còn lại đã đặt tên đúng
+ file html: 1.html, 2.html không có link bootstrap CDN, còn hardcode 
+ Sử dụng css riêng 
+ giao diện thân thiện dễ dùng nhưng các thành viên chưa thống nhất về giao diện
+ trong file readme đã nêu tên các thành viên và app tham khảo nhưng chưa có miêu tả chức năng
+ commit đúng, dễ hiểu

**Comment by haohoang97** [comment]
nhóm HMH nhận xét nhóm LSE
+Bài tập cá nhân: các thành viên trong nhóm đã nộp đủ 100% lượng bài tập
+Bài tập nhóm: đặt tên ảnh và html đúng yêu cầu, các giao diện vẽ tương đối đầy đủ chức năng, và đồng nhất với nhau.
         File html:  sử dụng bootstrap thuần, link với bootstrap CDN
         File Readme: đã nêu tên các thành viên, nội dung thì hơi ngắn nên chưa nói rõ được các chức năng
         Commit đúng, dễ hiểu

**Comment by Cuong97CC** [comment]
Nhóm Moonlight nhận xét nhóm S.M.L:
+Nhóm nộp bài đầy đủ, commit đúng.
+File html: có cả file css, cả file less.
+Không có file readme, k nêu đc thành viên và chức năng của app.
+Có quá nhiều file khác nộp không đúng yêu cầu, không có liên quan đến app.

**Comment by PvDuke** [comment]
Nhóm Corgi nhận xét nhóm H3T:
Bài tập nhóm: tên ảnh và html đúng yêu cầu, các giao diện đồng nhất, thực hiện chức năng chính của trang web, đã sử dụng bootstrap thuần, có điều các bạn gộp chung cả bt cá nhân vào bt nhóm.
Bài tập cá nhân: thành viên nhóm đã 100% hoàn thành bài tập 4 tuần, đặt tên đúng.
File Readme: nội dung đầy đủ, rõ ràng, có danh sách thành viên. 
Commit: chưa thể hiện rõ những việc đã làm

**Comment by khuyen97** [comment]
Nhóm Moonlight nhận xét nhóm S.M.L:
BT cá nhân: có thành viên chưa làm hết bài tập, tên file ảnh còn sai.
BT nhóm:
+Nhóm nộp bài đầy đủ, commit đúng.
+Giao diện tương đối đồng nhất.
+Đặt tên nhóm không đúng yêu cầu.
+Có 2 thư mục nộp bài nhóm.
+Một số file html chưa link đến bootstrap cdn trên mạng.
+Còn sử dụng css riêng.
+Không có file readme, không nêu được thành viên và chức năng của app.
+Có quá nhiều file khác nộp không đúng yêu cầu.

**Comment by nguyentienviet123456** [comment]
K-59 nhận xét nhóm LOL2VN:
BT cá nhân: chuẩn
BT nhóm: 
- commit chuẩn, đầy đủ yêu cầu như file readme, có dùng boostrap
-a little bit hardcode

**Comment by quita2004** [comment]
Nhóm LSE nhận xét nhóm NoName:
-Bài tập cá nhân: bạn Lưu Văn Phúc đặt tên file ko đúng qui định:GIT.jpg, HTML-CSS.jpg, JQuery.jpg, JS.jpg, WEB.jpg.chưa xoá các file cũ đi: có 2 file về htmlcss và jquery. Các bạn còn lại đều đã nộp đầy đủ và đúng yêu cầu.
-Bài tập nhóm:
  + File readme.md tốt.
  + Các ảnh chụp màn hình trên thiết bị di động tốt, file html: sử dụng  ionic.
  + Các commit đã đúng yêu cầu.

**Comment by DoHaiBinh** [comment]
Nhóm ĐMX nhận xét nhóm K-59:
- Bài tập cá nhân: 
   + Cá nhân hoàn thành bài tập về nhà đầy đủ
   + Đặt tên và commit còn chưa đúng yêu cầu
- Bài tập nhóm: 
   + Gửi đủ ảnh, đủ file html.
   + File readme.md đúng yêu cầu.
   + Code chuẩn, sử dụng bootstrap thuần, link chuẩn.
   + Các commit đúng yêu cầu.

**Comment by tranvancuong2597** [comment]
Nhóm TTAC nhận xét nhóm ĐMX:
       *Bài tập cá nhân:
             - Cá nhân đã hoàn thành bài tập về nhà đầy đủ. Một bạn chưa xoá những file ảnh không đúng theo fomat.
       *Bài tập nhóm:
             - Gửi đủ số lượng ảnh, file html theo yêu cầu
             - File readme.md tốt
             - Các commit đúng yêu cầu
             - Sử dụng bootstrap thuần

**Comment by xuanvuong97** [comment]
Nhóm **No Name** nhận xét nhóm **TTAC**:

**Bài tập cá nhân:**
  - Các thành viên nộp bài đầy đủ
  - Phần đặt tên có bạn Trần Đức Thọ đặt chưa đúng yêu cầu (Ruby.png)
  - Commit: bạn Trần Đức Thọ, Lê Phúc Ân, Trần Văn Cường commit không đúng yêu cầu

**Bài tập nhóm:**
  - Có 2 thư mục nộp bài nhóm (thư mục sai chưa xóa)
  - Gửi đủ số lượng ảnh, file html tối thiểu theo yêu cầu
  - File Readme.md và commit đúng yêu cầu
  - Có dùng bootstrap

**Comment by shaka189** [comment]
Nhóm ATTT nhận xét nhóm BKA: 
**Bài tập cá nhân:**
+ Các thành viên trong nhóm nộp đủ bài tập.
+ Nguyễn Quốc Cường, Lê Tuấn Sơn, Nguyễn Trung Hiếu còn đặt tên ảnh sai format 
+ Một số commit chưa đúng yêu cầu
**Bài tập nhóm:**
+ Bài tập nhóm nộp đầy đủ yêu cầu, ý tưởng tốt chưa phổ biến nhiều
+ Giao diện bootstrap thuần, đơn giản dễ sử dụng
+ File Readme.md đủ, đúng yêu cầu
+ 1 commit chưa đúng yêu cầu

**Comment by trungluong96** [comment]
Nhóm VIRUS nhận xét nhóm FallenBlossom:
Bài tập cá nhân:

- Đào Đức Hòa: chưa nộp đủ bài tập + đặt tên sai format 

- Còn lại đã nộp đủ và đặt tên đúng format

Bài tập nhóm:

- Bài tập nhóm nộp đầy đủ yêu cầu

- File Readme.md đủ, đúng yêu cầu

- Giao diện bootstrap thuần, đơn giản dễ sử dụng

**Comment by hawk262** [comment]
Nhóm S.M.L nhận xét nhóm VIRUS: 
Bài tập cá nhân:
- Các thành viên nộp bài tập đầy đủ.
Bài tập nhóm
- Nhóm nộp đầy đủ theo yêu cầu.
- Có sử dụng boostrap đơn giản, dễ nhìn.

**Comment by TranHongngoc** [comment]
Em thưa thầy . thầy có thể bổ sung nhóm NTT vào danh sách các nhóm trong  lớp được không ạ. ( lần trước  nhóm em up  sai tên . đã chỉnh lại rồi ạ . )

**Comment by truonganhhoang** [comment]
issue này đóng rồi, để chuyển sang issue tiếp theo nhóm em có tên rồi.

**Comment by TranHongngoc** [comment]
Vâng . em cảm ơn thầy ạ .
